#ifndef OPENING_H
#define OPENING_H

enum {
	OPENING_FADE_FIELDS      = 30,
	OPENING_FADE_SKIP_FIELDS = 6
};

enum {
	OPENING_FADE_VM_FRAMES = 10
};

#define OPENING_CDDA_TRACK_START_MS 0u

#define OPENING_CDDA_STOP_MS 151700

#define OPENING_USE_MODULE 1

#define OPENING_MODULE_SKIP_ROWS 0

#define OPENING_CDDA_HOLD_CAP_MS 9000u

#endif
